---
published: true
---
This blogpost is generated by ChatGPT from an outline. The outline is provided at the bottom. This particular post took quite a few tries. At first I was generating all the blogposts in a single conversation. When I tried to generate this one it failed multiple times and when it succeeded I wasn't happy with the results. Eventually I created a new conversation which resulted in the following blogpost. It is closer to what I had imagined, but it isn't quite understanding that level 1 and 25 for smartphones is the present/past while even level 1 for metaverse is the future. I am sure that altering the outline a bit can change fix this. Either way it was interesting to watch the language change significantly for the same prompt in a new conversation. I had not considered that conversation context might influence the generation so much.

The Metaverse is an exciting and rapidly developing technology, but it's also poorly communicated. It's important to remember that revolutions always start at the ground level and build up, but the way we communicate about these revolutions often starts at a much higher level. For example, when smart phones first became popular, they were simply a way to read emails and chat while waiting for the bus. But now, smart phones are a integral part of a massive global economy, with behemoth corporations built on the premise that everyone has a computer in their pocket.

The Metaverse is currently at a similar ground level. It's a place where you can work from anywhere, whether that's your couch, porch, beach house, or bus stop. But it has the potential to become so much more. Imagine a world where everything that currently runs on a 2D computer screen is translated into a 3D virtual space. This would have massive implications for code, data, and anything else that is big or complicated, such as structural blueprints.

One thing to consider with any revolutionary technology is who is driving its adoption. In the case of the Metaverse, it's not the 30+ crowd that will determine its success or failure. It's the teens and twenty-somethings. They are the ones who are currently eating up the Metaverse, with games like Fortnite leading the way. The real challenge here will be creating hardware that is cheap and good enough for teens to buy. If the Metaverse can achieve 90% penetration with this demographic, the rest of the world will surely follow.

It's worth noting that Mark Zuckerberg is one of the people working on the Metaverse, but that doesn't mean he will succeed. In fact, it's possible that he will fail. The Innovator's Dilemma by Clayton Christensen provides one reason why this might be the case. Ultimately, only time will tell what the future holds for the Metaverse.


```
outline: 
- Metaverse is poorly communicated
- Revolutions start at level 1, but communication sometimes start at level 25
  - level 1 for smart phones: Read email/chat while waiting for the bus
  - level 25 for smart phones: A large economy with global behemoth corporations built on the premise that everyone has computers in their pockets
  - Level 1 for metaverse: You can now work from your couch/porch/beachhouse/bustop as you don't need your screens
  - Level 25 for metaverse: Everything running in 2d on computers now gets translated to 3d in the metaverse, a new set of global behemoth corporations
    - Massive implications for code, data and anything big or complicated (think structural blueprints)
- Whether revolutions succeed or not is decided by teens and twenty-somethings, not the 30+ crowd (parents dont get it, not now, not ever)
  - Teens are eating the metaverse shit up (fortnite)
  - The real challenge here is creating hardware that is cheap and good enough that teens can and will buy it, just like with the smart phone revolution, if you get 90% penetration with the teens then the rest of the world will follow.
- Not saying that Zuckerberg will succeed with whatever he is working on
    - Actually i am pretty sure he will fail, see Clayton Christensens "The innovators dilemma" for one reason why
```
